### ISSUE TITLE
question about interpretation

### ISSUE THREAD

**Issue by tissatussa** [mrdcvlsc/analyse-pgn#11]
thank you for this nice program !
i compiled it on Linux and it seems to work well.

but i wonder about the interpretation .. here's one of my recent own games, see https://lichess.org/iFSd9qaS/black :

```
Tom Scheper   --   Roelof Berkepeis
SVPS interne competitie  Enschede, Holland 
2024.05.06  0-1
```

```
2.c4 e5 
good! (-0.65)
( 2...e6 BEST (-0.24) )
```

why "good!" here ?
while -0.24 is best, my move ...e5 scores -0.65 which is about 3x worse !?

same with :

```
6.Qc2 Qe7 
good! (+0.16)
( 6...O-O BEST (+0.65) )
```

and the difference between best move and my move is relatively small here :

```
7.Nb5 Bb6 
inaccurate? (+0.95)
( 7...O-O BEST (+1.55) )
```

can you elaborate on this ?
is my reasoning wrong ?

---

btw. lately the website chess.com posted an article about their `CAPS` analysing method :

How does Game Review work?
https://support.chess.com/en/articles/8584089-how-does-game-review-work

and this linked article :

How is Accuracy in analysis determined?
https://support.chess.com/en/articles/8708970-how-is-accuracy-in-analysis-determined

this CAPS method is generally described, but its internal functioning is revealed nowhere ..

[ i'm on Xubuntu 22.04 ]

**Comment by mrdcvlsc** [comment]
@tissatussa I haven't worked on this program or looked at the code for a while. Though, I want to work on it when I have more free time in the future. **But! Here's what I remember about how it works:**

- If the score is **negative**, it means the **black** pieces are doing better. If the score is **positive**, it means the **white** pieces are doing better.
    - The bigger the **negative** number, the better for _BLACK_.
    - The bigger the **positive** number, the better for _WHITE_.

**Or It could be like this:**

- Negative evaluation means your enemy is winning, and a positive evaluation means you're winning. The bigger the negative number, the more your enemy is winning. The bigger the positive number, the more you're winning.

I could figure out which is which by looking at my code, but I’m not yet ready to confront the potential abominable code I might have written in the past.

**Comment by mrdcvlsc** [comment]
> and the difference between best move and my move is relatively small here :
    7.Nb5 Bb6 
    inaccurate? (+0.95)
    ( 7...O-O BEST (+1.55) )
    
As I have observed for modern chess engines this advantage from `+0.95` to `+1.55` is actually **not relatively small** and could be potentially winning for the side of `+1.55`.

I also remembered that the evaluations in this program just get the current evaluation of the chess engine being used, compare it to the previous evaluation for the previous move, then base on the difference in the evaluations it outputs the interpretations.
